runtime: nodejs18
env: flex

env_variables:
  PORT: "8080"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

network:
  forwarded_ports:
    - 8080
    - 3000
